name: Weekly Notes Generator

on:
  push:
    branches:
      - main

jobs:
  notes-gen:
    runs-on: ubuntu-latest
    container:
      image: pandoc/latex
      options: --entrypoint /bin/bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate Weekly Summary
        run : |
          pandoc readme.md -o readme.pdf

      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: readme.pdf
          path: readme.pdf
        
  notes-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Download Generated PDF
        uses: actions/download-artifact@v2
        with:
          name: readme.pdf
      
      - name: Commit & Push PDF
        runs: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add .
          git commit -a -m "Automated Notes Build $(date '+%Y-%m-%d')"
          git push origin main


